# Generated by Django 5.2.1 on 2025-05-31 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('data_expiracao', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='plataforma.aplicacao')),
            ],
        ),
        migrations.CreateModel(
            name='RenovacaoLicenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_renovacao', models.DateField(auto_now_add=True)),
                ('nova_data_expiracao', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('licenca_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovacoes', to='plataforma.licenca')),
            ],
        ),
    ]
