# Generated by Django 5.2.1 on 2025-06-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_aplicacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenca',
            options={'verbose_name': 'Licença', 'verbose_name_plural': 'Licenças'},
        ),
        migrations.AlterModelOptions(
            name='renovacaolicenca',
            options={'verbose_name': 'Renovação de Licença', 'verbose_name_plural': 'Renovações de Licença'},
        ),
    ]
